Another try

diff --git a/.github/workflows/pylint_check.yaml b/.github/workflows/pylint_check.yaml
--- a/.github/workflows/pylint_check.yaml
+++ b/.github/workflows/pylint_check.yaml
@@ -48,13 +48,13 @@ jobs:
         run: 'python3 -m pip install --upgrade --no-cache-dir numpy wheel'
       - name: Install Python pygdal
         shell: bash
-        run: 'sudo python3 -m pip install --no-cache-dir pygdal==3.0.4.*'
+        run: 'python3 -m pip install --no-cache-dir pygdal==3.0.4.*'
       - name: Install system requirements from source
         shell: bash
-        run: '[ -s "packages.txt" ] && (sudo cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
+        run: '[ -s "packages.txt" ] && (sudo cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "Error while installing additional packages")'
       - name: Install Python requirements from source
         shell: bash
-        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "No Python packages to install")'
+        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "Error while installing additional python packages")'
       - name: Run action pylint script
         shell: bash
         run: '[ -s ".github/workflows/action_pylint.sh" ] && (chmod +x ".github/workflows/action_pylint.sh" && ./.github/workflows/action_pylint.sh) || (echo "Error running shell script")'
